spring.application.name=shortly
app.shortly.shorten.host=http://localhost:8080



# Fixed JDBC URL for an in-memory database named "testdb"
spring.datasource.url=jdbc:mysql://localhost:3306/shortlydb
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=ankit@123


#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379



